# Configuration file
SUBSCRIPTION_ID: 'aml_subscription_id'
RESOURCE_GROUP: 'aml_rg'
WORKSPACE_NAME: 'aml_wn'

COMPUTE_NAME: 'compute_name'

# Docker settings
DOCKER_BASE_IMAGE: 'docker_image_uri'

RUN_TYPE: 'ort'
ENV_NAME: 'env_name'

# Path to deepspeed config file
DS_CONFIG_PATH: 'zero1.json'

# Environment variables
ENVIRONMENT_VARIABLES:
  ORTMODULE_ENABLE_LABEL_SPARSITY_OPT: '1'

# Tags
TAGS:
  env_type: 'label_sarsity'



